package dev.ryanhcode.sable.api.physics.force;

// AUTO-GENERATED STUB for dev.ryanhcode.sable.api.physics.force.ForceGroups
// Source API: Sable/Veil 1.21.1. Physics and custom rendering are INERT by design.
// Regenerate instead of hand-editing.
@SuppressWarnings({"unchecked", "unused", "rawtypes"})
public class ForceGroups {
    public static final net.minecraft.resources.ResourceKey<net.minecraft.core.Registry<dev.ryanhcode.sable.api.physics.force.ForceGroup>> REGISTRY_KEY = null;
    public static final net.minecraft.core.Registry<dev.ryanhcode.sable.api.physics.force.ForceGroup> REGISTRY = null;
    public static final foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.api.physics.force.ForceGroup> GRAVITY = new foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.api.physics.force.ForceGroup>() { @Override public net.minecraft.resources.ResourceKey<T> getResourceKey() { return null; }  @Override public boolean isPresent() { return false; }  @Override public T get() { return null; }  @Override public net.minecraft.core.Holder<T> asHolder() { return null; } };
    public static final foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.api.physics.force.ForceGroup> DRAG = new foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.api.physics.force.ForceGroup>() { @Override public net.minecraft.resources.ResourceKey<T> getResourceKey() { return null; }  @Override public boolean isPresent() { return false; }  @Override public T get() { return null; }  @Override public net.minecraft.core.Holder<T> asHolder() { return null; } };
    public static final foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.api.physics.force.ForceGroup> LEVITATION = new foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.api.physics.force.ForceGroup>() { @Override public net.minecraft.resources.ResourceKey<T> getResourceKey() { return null; }  @Override public boolean isPresent() { return false; }  @Override public T get() { return null; }  @Override public net.minecraft.core.Holder<T> asHolder() { return null; } };
    public static final foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.api.physics.force.ForceGroup> BALLOON_LIFT = new foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.api.physics.force.ForceGroup>() { @Override public net.minecraft.resources.ResourceKey<T> getResourceKey() { return null; }  @Override public boolean isPresent() { return false; }  @Override public T get() { return null; }  @Override public net.minecraft.core.Holder<T> asHolder() { return null; } };
    public static final foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.api.physics.force.ForceGroup> PROPULSION = new foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.api.physics.force.ForceGroup>() { @Override public net.minecraft.resources.ResourceKey<T> getResourceKey() { return null; }  @Override public boolean isPresent() { return false; }  @Override public T get() { return null; }  @Override public net.minecraft.core.Holder<T> asHolder() { return null; } };
    public static final foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.api.physics.force.ForceGroup> LIFT = new foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.api.physics.force.ForceGroup>() { @Override public net.minecraft.resources.ResourceKey<T> getResourceKey() { return null; }  @Override public boolean isPresent() { return false; }  @Override public T get() { return null; }  @Override public net.minecraft.core.Holder<T> asHolder() { return null; } };
    public static final foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.api.physics.force.ForceGroup> MAGNETIC_FORCE = new foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.api.physics.force.ForceGroup>() { @Override public net.minecraft.resources.ResourceKey<T> getResourceKey() { return null; }  @Override public boolean isPresent() { return false; }  @Override public T get() { return null; }  @Override public net.minecraft.core.Holder<T> asHolder() { return null; } };
    public ForceGroups() {}
    public static void register() {}
    public static int count() { return 0; }
}
