package dev.ryanhcode.sable.physics.config.block_properties;

// AUTO-GENERATED STUB for dev.ryanhcode.sable.physics.config.block_properties.PhysicsBlockPropertyTypes
// Source API: Sable/Veil 1.21.1. Physics and custom rendering are INERT by design.
// Regenerate instead of hand-editing.
@SuppressWarnings({"unchecked", "unused", "rawtypes"})
public class PhysicsBlockPropertyTypes {
    public static final net.minecraft.resources.ResourceKey<net.minecraft.core.Registry<dev.ryanhcode.sable.physics.config.block_properties.PhysicsBlockPropertyTypes.PhysicsBlockPropertyType<?>>> REGISTRY_KEY = null;
    public static final foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.physics.config.block_properties.PhysicsBlockPropertyTypes.PhysicsBlockPropertyType<java.lang.Double>> MASS = new foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.physics.config.block_properties.PhysicsBlockPropertyTypes.PhysicsBlockPropertyType<java.lang.Double>>() { @Override public net.minecraft.resources.ResourceKey<T> getResourceKey() { return null; }  @Override public boolean isPresent() { return false; }  @Override public T get() { return null; }  @Override public net.minecraft.core.Holder<T> asHolder() { return null; } };
    public static final foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.physics.config.block_properties.PhysicsBlockPropertyTypes.PhysicsBlockPropertyType<net.minecraft.world.phys.Vec3>> INERTIA = new foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.physics.config.block_properties.PhysicsBlockPropertyTypes.PhysicsBlockPropertyType<net.minecraft.world.phys.Vec3>>() { @Override public net.minecraft.resources.ResourceKey<T> getResourceKey() { return null; }  @Override public boolean isPresent() { return false; }  @Override public T get() { return null; }  @Override public net.minecraft.core.Holder<T> asHolder() { return null; } };
    public static final foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.physics.config.block_properties.PhysicsBlockPropertyTypes.PhysicsBlockPropertyType<java.lang.Double>> VOLUME = new foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.physics.config.block_properties.PhysicsBlockPropertyTypes.PhysicsBlockPropertyType<java.lang.Double>>() { @Override public net.minecraft.resources.ResourceKey<T> getResourceKey() { return null; }  @Override public boolean isPresent() { return false; }  @Override public T get() { return null; }  @Override public net.minecraft.core.Holder<T> asHolder() { return null; } };
    public static final foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.physics.config.block_properties.PhysicsBlockPropertyTypes.PhysicsBlockPropertyType<java.lang.Double>> RESTITUTION = new foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.physics.config.block_properties.PhysicsBlockPropertyTypes.PhysicsBlockPropertyType<java.lang.Double>>() { @Override public net.minecraft.resources.ResourceKey<T> getResourceKey() { return null; }  @Override public boolean isPresent() { return false; }  @Override public T get() { return null; }  @Override public net.minecraft.core.Holder<T> asHolder() { return null; } };
    public static final foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.physics.config.block_properties.PhysicsBlockPropertyTypes.PhysicsBlockPropertyType<java.lang.Double>> FRICTION = new foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.physics.config.block_properties.PhysicsBlockPropertyTypes.PhysicsBlockPropertyType<java.lang.Double>>() { @Override public net.minecraft.resources.ResourceKey<T> getResourceKey() { return null; }  @Override public boolean isPresent() { return false; }  @Override public T get() { return null; }  @Override public net.minecraft.core.Holder<T> asHolder() { return null; } };
    public static final foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.physics.config.block_properties.PhysicsBlockPropertyTypes.PhysicsBlockPropertyType<java.lang.Boolean>> FRAGILE = new foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.physics.config.block_properties.PhysicsBlockPropertyTypes.PhysicsBlockPropertyType<java.lang.Boolean>>() { @Override public net.minecraft.resources.ResourceKey<T> getResourceKey() { return null; }  @Override public boolean isPresent() { return false; }  @Override public T get() { return null; }  @Override public net.minecraft.core.Holder<T> asHolder() { return null; } };
    public static final foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.physics.config.block_properties.PhysicsBlockPropertyTypes.PhysicsBlockPropertyType<java.lang.Object>> FLOATING_MATERIAL = new foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.physics.config.block_properties.PhysicsBlockPropertyTypes.PhysicsBlockPropertyType<java.lang.Object>>() { @Override public net.minecraft.resources.ResourceKey<T> getResourceKey() { return null; }  @Override public boolean isPresent() { return false; }  @Override public T get() { return null; }  @Override public net.minecraft.core.Holder<T> asHolder() { return null; } };
    public static final foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.physics.config.block_properties.PhysicsBlockPropertyTypes.PhysicsBlockPropertyType<java.lang.Double>> FLOATING_SCALE = new foundry.veil.platform.registry.RegistryObject<dev.ryanhcode.sable.physics.config.block_properties.PhysicsBlockPropertyTypes.PhysicsBlockPropertyType<java.lang.Double>>() { @Override public net.minecraft.resources.ResourceKey<T> getResourceKey() { return null; }  @Override public boolean isPresent() { return false; }  @Override public T get() { return null; }  @Override public net.minecraft.core.Holder<T> asHolder() { return null; } };
    public PhysicsBlockPropertyTypes() {}
    public static void register() {}
    public static int count() { return 0; }
    public static com.mojang.serialization.Codec<java.lang.Object> getPropertyCodec(java.lang.Object p0) { return null; }
    public static dev.ryanhcode.sable.physics.config.block_properties.PhysicsBlockPropertyTypes.PhysicsBlockPropertyType<?> getPropertyType(java.lang.Object p0) { return null; }
    static public record PhysicsBlockPropertyType<T>(int id, com.mojang.serialization.Codec<T> codec, T defaultValue) {
    }
}
